networks:
  rhtas:
    name: "rhtas"

services:
  rhtas-console-ui:
    image: localhost/devcontainer-rhtas-console-ui:latest
    build:
      dockerfile: ./Dockerfile
    security_opt:
      - "label=disable"
    userns_mode: "keep-id"
    environment:
      CONSOLE_API_URL: http://rhtas-console:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../..:/workspace:cached
    networks:
      - rhtas
